source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SamplePOD_Example', :exclusive => true do
  pod 'SamplePOD', :path => '../'
end

target 'SamplePOD_Tests', :exclusive => true do
  pod 'SamplePOD', :path => '../'

  
end
